[build]
  command = "npm run build" # Or "yarn build" or "react-scripts build" - whatever builds your React app
  publish = "dist"          # <--- CHANGE THIS LINE FROM "build" TO "dist"

[functions]
  directory = "supabase/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true