[build]
  command = "npm run build"
  publish = "dist"          

[functions]
  directory = "supabase/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # force = true  <--- THIS LINE HAS BEEN REMOVED