[build]
  command = "npm run build" # This runs 'vite build' as per your package.json
  publish = "dist"          # This tells Netlify to serve content from the 'dist' folder

[functions]
  directory = "supabase/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200